<?php
/** @var \Contestio\Connect\ViewModel\RouteChecker $viewModel */
$viewModel = $block->getData('view_model');

if ($viewModel->isContestioRoute() === false) {
    // If not contestio route, do not load React app
    return;
}

try {
    $metaData = $this->getMetaTags();
} catch (Exception $e) {
    $metaData = [];
}

// Card type
echo "<meta name='twitter:card' content='summary'>";

// Og url
if (isset($metaData['currentUrl'])) {
    echo "<meta property='og:url' content='".$metaData['currentUrl']."'>";
    echo "<meta property='twitter:url' content='".$metaData['currentUrl']."'>";
}

// Composer package version
if (isset($metaData['version'])) {
    echo "<meta data-contestio-version='".$metaData['version']."'>";
}

// Open graph and twitter
if (isset($metaData['title'])) {
    echo "<meta property='og:title' content='".$metaData['title']."'>";
    echo "<meta property='twitter:title' content='".$metaData['title']."'>";
}
if (isset($metaData['description'])) {
    echo "<meta property='og:description' content='".$metaData['description']."'>";
    echo "<meta property='twitter:description' content='".$metaData['description']."'>";
}
if (isset($metaData['image'])) {
    echo "<meta property='og:image' content='".$metaData['image']."'>";
    echo "<meta property='twitter:image' content='".$metaData['image']."'>";
}
if (isset($metaData['siteName'])) {
    echo "<meta property='og:site_name' content='".$metaData['siteName']."'>";
    echo "<meta property='twitter:site' content='".$metaData['siteName']."'>";
}
?>
